name: bob_empire_mobile
description: BOB EMPIRE Mobile App - Global AI Commerce Platform

version: 2.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Database & Auth
  supabase_flutter: ^2.3.4
  
  # Storage
  shared_preferences: ^2.2.2
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Audio & Voice
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.3.0
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Utils
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1
  device_info_plus: ^10.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700